import assert from 'node:assert/strict';
import { existsSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
const temporaryManifests=[['src/enemy1Manifest.js','export const ENEMY1_MANIFEST = {};\n'],['src/enemy2Manifest.js','export const ENEMY2_MANIFEST = {};\n'],['src/boss1Manifest.js','export const BOSS1_MANIFEST = {};\n']];
const created=[];for(const [path,source] of temporaryManifests){if(!existsSync(path)){writeFileSync(path,source);created.push(path);}}process.on('exit',()=>{for(const path of created){try{unlinkSync(path);}catch{}}});
globalThis.Phaser={Scene:class Scene{},BlendModes:{ADD:'ADD'},Math:{Between:(a)=>a,Clamp:(value,min,max)=>Math.max(min,Math.min(max,value)),Linear:(a,b,t)=>a+(b-a)*t},Utils:{Array:{GetRandom:(values)=>values[0],Shuffle:(values)=>values}}};
const {GameSceneV28}=await import('../src/GameSceneV28.js');const {GameSceneV29,reverseAttackFrameV29,reversedBladeTangentV29}=await import('../src/GameSceneV29.js');const {PIXELLAB_MANIFEST}=await import('../src/pixellabManifest.js');const {TUNING}=await import('../src/config.js');
assert.equal(PIXELLAB_MANIFEST.attack_1.sourceAnimation,'The_warrior_shifts_his_weight_forward_tightening_h');assert.equal(PIXELLAB_MANIFEST.attack_1.east,8);assert.equal(PIXELLAB_MANIFEST.attack_1.west,8);assert.equal(PIXELLAB_MANIFEST.attack_2.east,8);assert.equal(PIXELLAB_MANIFEST.attack_2.west,8);assert.deepEqual(TUNING.attackDurationsMs,[230,245,500]);assert.deepEqual(TUNING.attackActiveStartMs,[52,60,80]);assert.deepEqual(TUNING.attackActiveEndMs,[144,164,220]);assert.deepEqual(TUNING.attackRanges,[80,88,104]);

const attack1=Object.create(GameSceneV29.prototype);attack1.attackStartsAt=1000;attack1.comboStep=0;const attack1Times=[1000,1052,1098,1144,1230];const attack1Forward=attack1Times.map(time=>GameSceneV28.prototype.attackFrame.call(attack1,'attack_1','east',time));const attack1Reversed=attack1Times.map(time=>attack1.attackFrame('attack_1','east',time));assert.deepEqual(attack1Reversed,attack1Forward.map(frame=>7-frame));assert.equal(attack1Reversed[0],7);assert.equal(attack1Reversed.at(-1),0);

const attack2=Object.create(GameSceneV29.prototype);attack2.attackStartsAt=2000;attack2.comboStep=1;const attack2Times=[2000,2060,2112,2164,2245];const attack2Forward=attack2Times.map(time=>GameSceneV28.prototype.attackFrame.call(attack2,'attack_2','east',time));const attack2Reversed=attack2Times.map(time=>attack2.attackFrame('attack_2','east',time));assert.deepEqual(attack2Reversed,attack2Forward.map(frame=>7-frame));assert.equal(attack2Reversed[0],7);assert.equal(attack2Reversed.at(-1),0);

assert.equal(reverseAttackFrameV29('attack_1','west',0),7);assert.equal(reverseAttackFrameV29('attack_1','west',7),0);assert.equal(reverseAttackFrameV29('attack_2','east',0),7);assert.equal(reverseAttackFrameV29('attack_2','east',7),0);assert.equal(reverseAttackFrameV29('attack_3','east',5),5);
assert.deepEqual(reversedBladeTangentV29(4),{x:-8,y:-24});assert.deepEqual(reversedBladeTangentV29('attack_2',4),{x:22,y:20});assert.deepEqual(reversedBladeTangentV29('attack_2',3),{x:14,y:38});assert.deepEqual(reversedBladeTangentV29('attack_2',2),{x:-2,y:38});

const source=readFileSync('src/GameSceneV29.js','utf8');assert.match(source,/REVERSED_ATTACKS_V29=new Set\(\['attack_1','attack_2'\]\)/);assert.match(source,/count-1-clamped/);assert.match(source,/Number\(frame\)\+1/);assert.match(source,/reversedBladeTangentV29\(action,frame\)/);assert.doesNotMatch(source,/if\(action!==['"]attack_1['"]\)/);
const main=readFileSync('src/main.js','utf8'),v38=readFileSync('src/GameSceneV38.js','utf8'),v37=readFileSync('src/GameSceneV37.js','utf8'),v36=readFileSync('src/GameSceneV36.js','utf8'),v35=readFileSync('src/GameSceneV35.js','utf8'),v34=readFileSync('src/GameSceneV34.js','utf8'),v33=readFileSync('src/GameSceneV33.js','utf8'),v32=readFileSync('src/GameSceneV32.js','utf8'),v31=readFileSync('src/GameSceneV31.js','utf8'),v30=readFileSync('src/GameSceneV30.js','utf8');
assert.match(main,/import \{ GameSceneV38 \} from '\.\/GameSceneV38\.js'/);assert.match(main,/scene: \[GameSceneV38\]/);assert.match(main,/GameSceneV38 -> GameSceneV37 -> GameSceneV36 -> GameSceneV35 -> GameSceneV34 -> GameSceneV33 -> GameSceneV32 -> GameSceneV31 -> GameSceneV30 -> GameSceneV29 -> GameSceneV28/);assert.match(v38,/extends GameSceneV37/);assert.match(v37,/extends GameSceneV36/);assert.match(v36,/extends GameSceneV35/);assert.match(v35,/extends GameSceneV34/);assert.match(v34,/extends GameSceneV33/);assert.match(v33,/extends GameSceneV32/);assert.match(v32,/extends GameSceneV31/);assert.match(v31,/extends GameSceneV30/);assert.match(v30,/extends GameSceneV29/);
console.log('V29 reversed attack-1 and attack-2 verification passed beneath V38.');
