import assert from 'node:assert/strict';
import { existsSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
const temporaryManifests=[['src/enemy1Manifest.js','export const ENEMY1_MANIFEST = {};\n'],['src/enemy2Manifest.js','export const ENEMY2_MANIFEST = {};\n'],['src/boss1Manifest.js','export const BOSS1_MANIFEST = {};\n']];const created=[];for(const [path,source] of temporaryManifests){if(!existsSync(path)){writeFileSync(path,source);created.push(path);}}process.on('exit',()=>{for(const path of created){try{unlinkSync(path);}catch{}}});
globalThis.Phaser={Scene:class Scene{},BlendModes:{ADD:'ADD'},Math:{Between:(a)=>a,Clamp:(value,min,max)=>Math.max(min,Math.min(max,value))},Utils:{Array:{GetRandom:(values)=>values[0],Shuffle:(values)=>values}}};
const {EXPEDITION_V34,generateExpeditionStageV34,expandedRosterV34,GameSceneV34}=await import('../src/GameSceneV34.js');
assert.ok(EXPEDITION_V34.right-EXPEDITION_V34.left>=12000);assert.equal(EXPEDITION_V34.sectionsPerStage,8);assert.equal(EXPEDITION_V34.normalStageCount,4);assert.ok(EXPEDITION_V34.activationDistancePx>=800&&EXPEDITION_V34.activationDistancePx<=1000);
const stageLabels=[];for(let depth=0;depth<4;depth++){const room=generateExpeditionStageV34(42,depth,['duel','hunters','mixed','pressure'][depth]);stageLabels.push(room.label);assert.equal(room.grammar,'verticalRuinsExpedition');assert.equal(room.sections.length,8);assert.equal(room.checkpoints.length,8);assert.equal(room.lights.length,8);assert.equal(room.objects.length,3);assert.ok(room.worldWidth>=13000);assert.ok(room.groundSpawns.length>=18);assert.ok(room.perchSpawns.length>=10);assert.ok(room.platforms.length>=20);assert.ok(room.platforms.filter(spec=>spec.role==='upper').length>=5);for(let index=0;index<room.sections.length;index++){const section=room.sections[index];assert.equal(section.start,EXPEDITION_V34.left+index*EXPEDITION_V34.sectionWidth);assert.equal(section.end,section.start+EXPEDITION_V34.sectionWidth);if(index>0)assert.equal(section.start,room.sections[index-1].end);}assert.ok(new Set(room.floorSegments.map(spec=>spec.y)).size>=3);let realGapCount=0;for(const section of room.sections){const floors=room.floorSegments.filter(spec=>spec.section===section.id).sort((a,b)=>a.x-b.x);for(let index=1;index<floors.length;index++){const gap=floors[index].x-(floors[index-1].x+floors[index-1].w);if(gap>0){realGapCount++;assert.ok(gap<=128);}}}assert.ok(realGapCount>=2);assert.equal(room.collision.length,room.floorSegments.length+room.platforms.length);assert.ok(room.exitX>EXPEDITION_V34.right-400);}
assert.equal(new Set(stageLabels).size,4);assert.deepEqual([0,1,2,3].map(depth=>expandedRosterV34('mixed',depth).length),[10,12,14,16]);assert.equal(expandedRosterV34('elite',3,true).length,16);assert.ok(GameSceneV34.prototype.isBranchDepth(0));assert.ok(GameSceneV34.prototype.isBranchDepth(2));assert.equal(GameSceneV34.prototype.isBranchDepth(1),false);
const source=readFileSync('src/GameSceneV34.js','utf8');assert.match(source,/extends GameSceneV33/);assert.match(source,/ENVIRONMENT_ART_V30\.background\.key/);assert.match(source,/ENVIRONMENT_ART_V30\.architecture\.key/);assert.match(source,/tilePositionX=scroll\*\.22/);assert.match(source,/tilePositionX=scroll\*\.38/);assert.match(source,/setScrollFactor\(0\)/);assert.doesNotMatch(source,/ENVIRONMENT_ART_V30\.arches/);assert.match(source,/renderGothicTerrain\(\[\.\.\.layout\.floorSegments,\.\.\.layout\.platforms\]\)/);assert.match(source,/fallResetY/);assert.match(source,/updateCheckpointV34/);assert.match(source,/AREA CLEARED • REACH THE GREEN GATE/);assert.match(source,/depth===0\|\|depth===2/);assert.match(source,/\[10,12,14,16\]/);
const main=readFileSync('src/main.js','utf8'),v37=readFileSync('src/GameSceneV37.js','utf8'),v36=readFileSync('src/GameSceneV36.js','utf8'),v35=readFileSync('src/GameSceneV35.js','utf8');assert.match(main,/import \{ GameSceneV37 \} from '\.\/GameSceneV37\.js'/);assert.match(main,/scene: \[GameSceneV37\]/);assert.match(main,/GameSceneV37 -> GameSceneV36 -> GameSceneV35 -> GameSceneV34 -> GameSceneV33 -> GameSceneV32 -> GameSceneV31 -> GameSceneV30 -> GameSceneV29/);assert.match(v37,/extends GameSceneV36/);assert.match(v36,/extends GameSceneV35/);assert.match(v35,/extends GameSceneV34/);
console.log('V34 vertical ruins expedition verification passed beneath V37.');
