import { GameScene } from './GameScene.js';
import { TUNING } from './config.js';
import { PIXELLAB_MANIFEST } from './pixellabManifest.js';
import { ENEMY1_MANIFEST } from './enemy1Manifest.js';

const FALLBACK_ASSET_ROOT='./assets/v05/production58',PIXELLAB_ROOT='./assets/v05/pixellab_protagonist',ENEMY1_ROOT='./assets/v05/enemy1';
const ART_SCALE=.38,PIXELLAB_SCALE=1,PIXELLAB_ART_Y=72,ENEMY1_SCALE=1.4688,ENEMY1_ART_Y=66,ATTACK_LUNGE=[90,115,145],ATTACK_RECOIL=[28,36,48];
const VFX_GREEN=0x43ff57,VFX_GREEN_HOT=0xbfff8f,VFX_GREEN_CORE=0xf2ffe1;
const LOOP_FPS=Object.freeze({idle:8,run:14}),ONESHOT_FPS=Object.freeze({jump:12,fall:12,light_attack:18,heavy_attack:16,dash:18,hit:16,death:10});
const FALLBACK_SEQUENCES=Object.freeze({idle:{folder:'idle',frames:6},run:{folder:'run',frames:6},jump:{folder:'jump',frames:4},attack:{folder:'attack',frames:8},roll:{folder:'dodge',frames:8},hit:{folder:'hurt',frames:7},death:{folder:'death',frames:8}});
function fallbackKey(n,i){return`fallback-${n}-${String(i+1).padStart(2,'0')}`;} function pxKey(a,d,i){return`px-${a}-${d}-${String(i).padStart(3,'0')}`;} function enemyKey(a,d,i){return`enemy1-${a}-${d}-${String(i).padStart(3,'0')}`;}
export class GameSceneV05 extends GameScene{
 preload(){
  for(const[n,s]of Object.entries(FALLBACK_SEQUENCES))for(let i=0;i<s.frames;i++){const f=`${s.folder}_${String(i+1).padStart(2,'0')}.png`;this.load.image(fallbackKey(n,i),`${FALLBACK_ASSET_ROOT}/${s.folder}/${f}?v=approved-r2`);}
  for(const[a,ds]of Object.entries(PIXELLAB_MANIFEST))for(const d of['east','west'])for(let i=0;i<(ds[d]||0);i++){const f=`frame_${String(i).padStart(3,'0')}.png`;this.load.image(pxKey(a,d,i),`${PIXELLAB_ROOT}/${a}/${d}/${f}?v=pixellab-protagonist-2`);}
  for(const[a,ds]of Object.entries(ENEMY1_MANIFEST))for(const d of['east','west'])for(let i=0;i<(ds[d]||0);i++){const f=`frame_${String(i).padStart(3,'0')}.png`;this.load.image(enemyKey(a,d,i),`${ENEMY1_ROOT}/${a}/${d}/${f}?v=enemy1-1`);}
 }
 create(){super.create();this.hitAnimStartsAt=-Infinity;this.hitAnimEndsAt=-Infinity;this.deathAnimStartsAt=-Infinity;this.pixelState='idle';this.pixelStateStartedAt=this.time.now;this.pixelDirection='east';this.currentPixelKey='';this.attackFlash.setAlpha(0);this.attackArc.setVisible(false);this.player.art.setVisible(false);this.pixelArt=this.add.image(this.player.x,this.player.y+PIXELLAB_ART_Y,pxKey('idle','east',0)).setOrigin(.5,1).setScale(PIXELLAB_SCALE).setDepth(100);this.fxWasGrounded=!!this.player?.body?.blocked?.down;this.nextDashTrailAt=0;}
 createPlayer(x,y){const p=this.add.container(x,y),shadow=this.add.ellipse(0,25,48,11,0x000000,.44),aura=this.add.ellipse(0,4,54,90,VFX_GREEN,.055).setStrokeStyle(3,VFX_GREEN_HOT,.2),art=this.add.image(0,27,fallbackKey('idle',0)).setOrigin(.5,1).setScale(ART_SCALE),weaponProxy=this.add.rectangle(16,0,54,8,0xffffff,0).setOrigin(.08,.5);p.add([shadow,aura,art,weaponProxy]);p.art=art;p.aura=aura;p.weapon=weaponProxy;p.cape={setScale(){return this;}};this.physics.add.existing(p);p.body.setSize(28,54).setOffset(-14,-30).setCollideWorldBounds(true).setMaxVelocity(TUNING.rollSpeed,TUNING.maxFallSpeed);return p;}
 createEnemy(x,y,type){
  const sprite=this.add.container(x,y),shadow=this.add.ellipse(0,23,66,16,0x000000,.45),art=this.add.image(0,ENEMY1_ART_Y,enemyKey('patrol','east',0)).setOrigin(.5,1).setScale(ENEMY1_SCALE).setDepth(2);sprite.add([shadow,art]);sprite.art=art;sprite.weapon={setAngle(){return this;}};this.physics.add.existing(sprite);sprite.body.setSize(32,52).setOffset(-16,-27).setCollideWorldBounds(true).setMaxVelocity(300,TUNING.maxFallSpeed);
  const tell=this.add.circle(x,y-22,44,0xff304f,.08).setStrokeStyle(3,0xff5b72,.8).setVisible(false).setDepth(45),hpBarBg=this.add.rectangle(x,y-122,56,5,0x140a12,.8).setDepth(44),hpBar=this.add.rectangle(x-27,y-122,54,3,0xff6f8d,1).setOrigin(0,.5).setDepth(45);
  return{id:`enemy-${x}-${type}`,type:'enemy1',sprite,tell,hpBarBg,hpBar,hp:TUNING.enemyMaxHp,alive:true,state:'patrol',stateEndsAt:0,nextAttackAt:0,speed:58,attackRange:92,windupMs:230,patrolMin:x-150,patrolMax:x+150,patrolDir:type==='stalker'?-1:1,facing:type==='stalker'?-1:1,animState:'patrol',animStartedAt:0,attackDidHit:false,lungeStartedAt:0};
 }
 setEnemyAnim(e,a,t,force=false){if(!ENEMY1_MANIFEST[a])a='patrol';if(!force&&e.animState===a)return;e.animState=a;e.animStartedAt=t;}
 updateEnemyArt(e,t){if(!e.sprite?.art)return;let a=e.animState||'patrol',d=e.facing<0?'west':'east',meta=ENEMY1_MANIFEST[a]||ENEMY1_MANIFEST.patrol,count=meta?.[d]||1,elapsed=Math.max(0,t-(e.animStartedAt||0)),fps=a==='patrol'?8:(a==='lunge'?14:12),frame=a==='patrol'?Math.floor(elapsed/1000*fps)%count:Math.min(count-1,Math.floor(elapsed/1000*fps));e.sprite.art.setTexture(enemyKey(a,d,frame)).setScale(ENEMY1_SCALE).setPosition(0,ENEMY1_ART_Y).setOrigin(.5,1).setFlipX((d==='west'&&!!meta.mirrorWest)||(d==='east'&&!!meta.mirrorEast));}
 updateEnemy(e,t,index){
  if(!e.alive||this.dead)return;const b=e.sprite.body,dx=this.player.x-e.sprite.x,dist=Math.abs(dx),dy=Math.abs(this.player.y-e.sprite.y);e.tell.setPosition(e.sprite.x,e.sprite.y-22);e.hpBarBg.setPosition(e.sprite.x,e.sprite.y-122);e.hpBar.setPosition(e.sprite.x-27,e.sprite.y-122).setSize(54*(e.hp/TUNING.enemyMaxHp),3);
  if(e.state==='stagger'){b.velocity.x*=.84;this.setEnemyAnim(e,ENEMY1_MANIFEST.hit?'hit':'patrol',t);if(t>=e.stateEndsAt){e.state='patrol';this.setEnemyAnim(e,'patrol',t,true);}this.updateEnemyArt(e,t);return;}
  if(e.state==='windup'){b.setVelocityX(0);e.facing=dx<0?-1:1;this.setEnemyAnim(e,'patrol',t);if(t>=e.stateEndsAt){e.state='lunge';e.lungeStartedAt=t;e.stateEndsAt=t+390;e.attackDidHit=false;e.tell.setVisible(false);this.setEnemyAnim(e,'lunge',t,true);b.setVelocityX(e.facing*275);}this.updateEnemyArt(e,t);return;}
  if(e.state==='lunge'){b.setVelocityX(e.facing*275);if(!e.attackDidHit&&t-e.lungeStartedAt>80&&Math.abs(this.player.x-e.sprite.x)<=e.attackRange&&dy<64){e.attackDidHit=true;this.damagePlayer(t,e);}if(t>=e.stateEndsAt){e.state='recovery';e.stateEndsAt=t+300;b.setVelocityX(0);e.nextAttackAt=t+650;}this.updateEnemyArt(e,t);return;}
  if(e.state==='recovery'){b.velocity.x*=.78;if(t>=e.stateEndsAt){e.state='patrol';this.setEnemyAnim(e,'patrol',t,true);}this.updateEnemyArt(e,t);return;}
  if(dist<185&&dy<72&&t>=e.nextAttackAt){e.state='windup';e.stateEndsAt=t+e.windupMs;e.facing=dx<0?-1:1;b.setVelocityX(0);e.tell.setVisible(true).setScale(.7).setAlpha(.3);this.tweens.killTweensOf(e.tell);this.tweens.add({targets:e.tell,scale:1.25,alpha:.88,duration:e.windupMs,ease:'Quad.easeIn'});this.updateEnemyArt(e,t);return;}
  if(e.sprite.x<=e.patrolMin)e.patrolDir=1;else if(e.sprite.x>=e.patrolMax)e.patrolDir=-1;e.facing=e.patrolDir;b.setVelocityX(e.patrolDir*e.speed);this.setEnemyAnim(e,'patrol',t);this.updateEnemyArt(e,t);
 }
 setPixelState(n,t,f=false){if(!PIXELLAB_MANIFEST[n]||(!f&&this.pixelState===n))return;this.pixelState=n;this.pixelStateStartedAt=t;this.currentPixelKey='';}
 resolvePixelState(t){const b=this.player?.body;if(!b)return'idle';if(this.dead)return'death';if(t<this.hitAnimEndsAt)return'hit';if(this.state==='rolling')return'dash';if(this.state?.startsWith('attack-'))return this.comboStep===2?'heavy_attack':'light_attack';if(!b.blocked.down)return b.velocity.y<0?'jump':'fall';return this.state==='running'?'run':'idle';}
 frameForState(a,d,t){const c=PIXELLAB_MANIFEST[a]?.[d]||1,e=Math.max(0,t-this.pixelStateStartedAt);return LOOP_FPS[a]?Math.floor(e/1000*LOOP_FPS[a])%c:Math.min(c-1,Math.floor(e/1000*(ONESHOT_FPS[a]||12)));}
 updatePixelArt(t){if(!this.pixelArt)return;const a=this.resolvePixelState(t);this.setPixelState(a,t);const d=this.facing<0?'west':'east';if(d!==this.pixelDirection){this.pixelDirection=d;this.currentPixelKey='';}const k=pxKey(a,d,this.frameForState(a,d,t));if(k!==this.currentPixelKey){this.pixelArt.setTexture(k);this.currentPixelKey=k;}this.pixelArt.setPosition(this.player.x,this.player.y+PIXELLAB_ART_Y).setOrigin(.5,1).setScale(PIXELLAB_SCALE).setVisible(true);this.player.art.setVisible(false);}
 spawnGreenBurst(x,y,count=18,sx=66,sy=46,life=270){for(let i=0;i<count;i++){const s=Phaser.Math.Between(2,7),c=i%5===0?VFX_GREEN_CORE:i%2===0?VFX_GREEN_HOT:VFX_GREEN,p=this.add.circle(x,y,s,c,1).setDepth(115).setBlendMode(Phaser.BlendModes.ADD),dx=Phaser.Math.Between(-sx,sx),dy=Phaser.Math.Between(-sy,Math.max(6,sy*.4));this.tweens.add({targets:p,x:x+dx,y:y+dy,scale:.05,alpha:0,duration:Phaser.Math.Between(Math.max(130,life-60),life+100),ease:'Quad.easeOut',onComplete:()=>p.destroy()});}}
 spawnSwordFlare(step=0){const h=step===2,x=this.player.x+this.facing*(h?50:40),y=this.player.y+PIXELLAB_ART_Y-46,L=h?150:100;for(const[w,a,c,z]of[[h?25:17,.34,VFX_GREEN,107],[h?14:9,.68,VFX_GREEN_HOT,109],[h?6:4,1,VFX_GREEN_CORE,111]]){const r=this.add.rectangle(x,y,L,w,c,a).setOrigin(this.facing>0?0:.99,.5).setAngle(this.facing>0?-24:24).setDepth(z).setBlendMode(Phaser.BlendModes.ADD);this.tweens.add({targets:r,scaleX:h?1.65:1.45,scaleY:.08,alpha:0,duration:h?310:205,ease:'Quad.easeOut',onComplete:()=>r.destroy()});}this.spawnGreenBurst(x+this.facing*(h?76:48),y,h?34:20,h?82:54,h?62:40,h?390:280);}
 spawnDashTrail(){const backX=this.player.x-this.facing*34,backY=this.player.y+PIXELLAB_ART_Y-76;for(let i=0;i<3;i++){const y=backY+Phaser.Math.Between(-18,18),st=this.add.rectangle(backX,y,Phaser.Math.Between(50,88),Phaser.Math.Between(4,9),i===0?VFX_GREEN_CORE:i===1?VFX_GREEN_HOT:VFX_GREEN,i===0?.72:.52).setOrigin(this.facing>0?1:0,.5).setDepth(94).setBlendMode(Phaser.BlendModes.ADD);this.tweens.add({targets:st,x:backX-this.facing*Phaser.Math.Between(45,78),scaleX:1.9,scaleY:.25,alpha:0,duration:190,ease:'Quad.easeOut',onComplete:()=>st.destroy()});}for(let i=0;i<4;i++){const p=this.add.circle(backX,backY+Phaser.Math.Between(-20,20),Phaser.Math.Between(2,5),VFX_GREEN_HOT,.9).setDepth(95).setBlendMode(Phaser.BlendModes.ADD);this.tweens.add({targets:p,x:backX-this.facing*Phaser.Math.Between(35,80),y:p.y+Phaser.Math.Between(-14,14),alpha:0,scale:.1,duration:Phaser.Math.Between(130,210),onComplete:()=>p.destroy()});}}
 spawnLandingBurst(){const x=this.player.x,y=this.player.y+28;for(const d of[-1,1])for(let i=0;i<3;i++){const s=this.add.rectangle(x,y-i*3,38+i*12,3+i,VFX_GREEN_HOT,.72).setOrigin(d<0?1:0,.5).setDepth(96).setBlendMode(Phaser.BlendModes.ADD);this.tweens.add({targets:s,x:x+d*(50+i*14),scaleX:1.7,alpha:0,duration:220,ease:'Quad.easeOut',onComplete:()=>s.destroy()});}this.spawnGreenBurst(x,y-3,18,52,28,250);}
 startAttack(t,s=null){super.startAttack(t,s);const b=this.player?.body;if(b?.blocked?.down)b.velocity.x+=this.facing*(ATTACK_LUNGE[this.comboStep]||ATTACK_LUNGE[0]);this.setPixelState(this.comboStep===2?'heavy_attack':'light_attack',t,true);this.spawnSwordFlare(this.comboStep);}
 damageEnemy(e,s){if(!e?.alive)return;const hp=e.hp;super.damageEnemy(e,s);if(e.hp>=hp)return;if(e.alive)this.setEnemyAnim(e,ENEMY1_MANIFEST.hit?'hit':'patrol',this.time.now,true);const b=this.player?.body;if(b)b.velocity.x-=this.facing*(ATTACK_RECOIL[s]||ATTACK_RECOIL[0]);this.spawnImpactBurst(e.sprite.x,e.sprite.y-8,s);}
 spawnImpactBurst(x,y,s){const h=s===2,R=h?52:s===1?38:30;for(let i=0;i<3;i++){const r=this.add.circle(x,y,5,0xffffff,0).setStrokeStyle(h?6:5,i===0?VFX_GREEN_CORE:i===1?VFX_GREEN_HOT:VFX_GREEN,1-i*.18).setDepth(116).setBlendMode(Phaser.BlendModes.ADD);this.tweens.add({targets:r,scale:(R+i*13)/5,alpha:0,duration:(h?280:205)+i*45,ease:'Quad.easeOut',onComplete:()=>r.destroy()});}this.spawnGreenBurst(x,y,h?38:24,h?90:62,h?68:46,h?430:320);}
 startRoll(t,b){this.lastRollAt=t;this.rollEndsAt=t+TUNING.rollDurationMs;this.state='rolling';b.setVelocityX(this.facing*TUNING.rollSpeed);this.tweens.killTweensOf(this.player);this.player.setAlpha(1);this.setPixelState('dash',t,true);const bx=this.player.x-this.facing*30,by=this.player.y+PIXELLAB_ART_Y-76;this.spawnGreenBurst(bx,by,18,42,30,260);this.nextDashTrailAt=t;}
 damagePlayer(t,e){const hp=this.playerHp;super.damagePlayer(t,e);if(this.playerHp<hp){this.tweens.killTweensOf(this.player);this.player.setAlpha(1);if(!this.dead){this.hitAnimStartsAt=t;this.hitAnimEndsAt=t+420;this.setPixelState('hit',t,true);}}}
 killPlayer(){const now=this.time.now;this.deathAnimStartsAt=now;super.killPlayer();this.setPixelState('death',now,true);this.deathPanel.bg.setVisible(false);this.deathPanel.title.setVisible(false);const deathFrames=PIXELLAB_MANIFEST.death?.[this.facing<0?'west':'east']||13;const deathDurationMs=Math.ceil((deathFrames-1)/(ONESHOT_FPS.death||10)*1000)+220;this.time.delayedCall(deathDurationMs,()=>{if(!this.dead)return;this.deathPanel.bg.setSize(this.scale.width,this.scale.height).setVisible(true);this.deathPanel.title.setPosition(this.scale.width/2,this.scale.height/2).setVisible(true);});}
 drawAttackArc(){this.attackArc.clear();this.attackArc.setVisible(false);}
 update(t,d){super.update(t,d);if(!this.player)return;this.updatePixelArt(t);const b=this.player.body,g=!!b?.blocked?.down;if(this.state==='rolling'&&t>=this.nextDashTrailAt){this.spawnDashTrail();this.nextDashTrailAt=t+22;}if(g&&!this.fxWasGrounded&&Math.abs(b?.velocity?.y||0)<40)this.spawnLandingBurst();this.fxWasGrounded=g;const sg=Math.min(.13,Math.abs(b?.velocity?.x||0)/5000);this.player.aura.setAlpha(.065+sg).setScale(1+sg*2.1);if(this.debug?.text)this.debug.setText(this.debug.text.replace('DARKBOUND v0.4.0','DARKBOUND v0.8.6 ENEMY FLOOR ALIGN'));}
}